##########################################################################
##  v      #                  The Coq Proof Assistant                   ##
## <O___,, # CNRS-Ecole Polytechnique-INRIA Futurs-Universite Paris Sud ##
##   \VV/  #                                                            ##
##    //   #   Makefile automagically generated by coq_makefile V8.2    ##
##########################################################################

# WARNING
#
# This Makefile has been automagically generated
# Edit at your own risks !
#
# END OF WARNING

#
# This Makefile was generated by the command line :
# coq_makefile -f Make -o Makefile 
#

#########################
#                       #
# Libraries definition. #
#                       #
#########################

OCAMLLIBS:=
COQLIBS:= -R . DistributedReferenceCounting
COQDOCLIBS:=-R . DistributedReferenceCounting

##########################
#                        #
# Variables definitions. #
#                        #
##########################

CAMLP4LIB:=$(shell $(CAMLBIN)camlp5 -where 2> /dev/null || $(CAMLBIN)camlp4 -where)
CAMLP4:=$(notdir $(CAMLP4LIB))
COQSRC:=-I $(COQTOP)/kernel -I $(COQTOP)/lib \
  -I $(COQTOP)/library -I $(COQTOP)/parsing \
  -I $(COQTOP)/pretyping -I $(COQTOP)/interp \
  -I $(COQTOP)/proofs -I $(COQTOP)/syntax -I $(COQTOP)/tactics \
  -I $(COQTOP)/toplevel -I $(COQTOP)/contrib/correctness \
  -I $(COQTOP)/contrib/extraction -I $(COQTOP)/contrib/field \
  -I $(COQTOP)/contrib/fourier -I $(COQTOP)/contrib/graphs \
  -I $(COQTOP)/contrib/interface -I $(COQTOP)/contrib/jprover \
  -I $(COQTOP)/contrib/omega -I $(COQTOP)/contrib/romega \
  -I $(COQTOP)/contrib/ring -I $(COQTOP)/contrib/xml \
  -I $(CAMLP4LIB)
ZFLAGS:=$(OCAMLLIBS) $(COQSRC)
OPT:=
COQFLAGS:=-q $(OPT) $(COQLIBS) $(OTHERFLAGS) $(COQ_XML)
COQC:=$(COQBIN)coqc
COQDEP:=$(COQBIN)coqdep -c
GALLINA:=$(COQBIN)gallina
COQDOC:=$(COQBIN)coqdoc
CAMLC:=$(CAMLBIN)ocamlc -rectypes -c
CAMLOPTC:=$(CAMLBIN)ocamlopt -c
CAMLLINK:=$(CAMLBIN)ocamlc
CAMLOPTLINK:=$(CAMLBIN)ocamlopt
GRAMMARS:=grammar.cma
CAMLP4EXTEND:=pa_extend.cmo pa_macro.cmo q_MLast.cmo
PP:=-pp "$(CAMLBIN)$(CAMLP4)o -I . -I $(COQTOP)/parsing $(CAMLP4EXTEND) $(GRAMMARS) -impl"

###################################
#                                 #
# Definition of the "all" target. #
#                                 #
###################################

VFILES:=./abstract/finite.v\
  ./abstract/abstract_machine.v\
  ./abstract/sigma2.v\
  ./abstract/table2.v\
  ./abstract/sum.v\
  ./abstract/table.v\
  ./abstract/reduce.v\
  ./abstract/fifo.v\
  ./abstract/bibli.v\
  ./expose.v\
  ./machine2/invariant4.v\
  ./machine2/invariant2.v\
  ./machine2/liveness.v\
  ./machine2/invariant8.v\
  ./machine2/cardinal.v\
  ./machine2/invariant6.v\
  ./machine2/invariant3.v\
  ./machine2/alternate.v\
  ./machine2/comm.v\
  ./machine2/invariant7.v\
  ./machine2/invariant0.v\
  ./machine2/invariant1.v\
  ./machine2/machine.v\
  ./machine2/invariant5.v\
  ./machine3/invariant4.v\
  ./machine3/invariant2.v\
  ./machine3/still_to_prove.v\
  ./machine3/cardinal.v\
  ./machine3/invariant6.v\
  ./machine3/invariant3.v\
  ./machine3/alternate.v\
  ./machine3/comm.v\
  ./machine3/invariant0.v\
  ./machine3/invariant1.v\
  ./machine3/machine.v\
  ./machine3/invariant5.v\
  ./machine0/table_act.v\
  ./machine0/init.v\
  ./machine0/rece_copy3.v\
  ./machine0/rece_copy1.v\
  ./machine0/counting.v\
  ./machine0/rece_inc.v\
  ./machine0/rece_dec.v\
  ./machine0/copy.v\
  ./machine0/del.v\
  ./machine0/rece_copy2.v\
  ./machine0/mess_act.v\
  ./machine0/machine.v\
  ./machine0/evol.v\
  ./machine1/invariant4.v\
  ./machine1/invariant2.v\
  ./machine1/invariant8.v\
  ./machine1/cardinal.v\
  ./machine1/invariant6.v\
  ./machine1/invariant3.v\
  ./machine1/alternate.v\
  ./machine1/comm.v\
  ./machine1/invariant7.v\
  ./machine1/invariant0.v\
  ./machine1/invariant1.v\
  ./machine1/machine.v\
  ./machine1/invariant5.v\
  ./machine4/invariant4.v\
  ./machine4/invariant2.v\
  ./machine4/invariant8.v\
  ./machine4/cardinal.v\
  ./machine4/invariant6.v\
  ./machine4/invariant3.v\
  ./machine4/alternate.v\
  ./machine4/comm.v\
  ./machine4/invariant7.v\
  ./machine4/invariant0.v\
  ./machine4/invariant1.v\
  ./machine4/machine.v\
  ./machine4/invariant5.v
VOFILES:=$(VFILES:.v=.vo)
GLOBFILES:=$(VFILES:.v=.glob)
VIFILES:=$(VFILES:.v=.vi)
GFILES:=$(VFILES:.v=.g)
HTMLFILES:=$(VFILES:.v=.html)
GHTMLFILES:=$(VFILES:.v=.g.html)

all: $(VOFILES) 
spec: $(VIFILES)

gallina: $(GFILES)

html: $(GLOBFILES) $(VFILES)
	- mkdir html
	$(COQDOC) -toc -html $(COQDOCLIBS) -d html $(VFILES)

gallinahtml: $(GLOBFILES) $(VFILES)
	- mkdir html
	$(COQDOC) -toc -html -g $(COQDOCLIBS) -d html $(VFILES)

all.ps: $(VFILES)
	$(COQDOC) -toc -ps $(COQDOCLIBS) -o $@ `$(COQDEP) -sort -suffix .v $(VFILES)`

all-gal.ps: $(VFILES)
	$(COQDOC) -toc -ps -g $(COQDOCLIBS) -o $@ `$(COQDEP) -sort -suffix .v $(VFILES)`



####################
#                  #
# Special targets. #
#                  #
####################

.PHONY: all opt byte archclean clean install depend html

%.vo %.glob: %.v
	$(COQC) -dump-glob $*.glob $(COQDEBUG) $(COQFLAGS) $*

%.vi: %.v
	$(COQC) -i $(COQDEBUG) $(COQFLAGS) $*

%.g: %.v
	$(GALLINA) $<

%.tex: %.v
	$(COQDOC) -latex $< -o $@

%.html: %.v %.glob
	$(COQDOC) -glob-from $*.glob  -html $< -o $@

%.g.tex: %.v
	$(COQDOC) -latex -g $< -o $@

%.g.html: %.v %.glob
	$(COQDOC) -glob-from $*.glob -html -g $< -o $@

%.v.d: %.v
	$(COQDEP) -glob -slash $(COQLIBS) "$<" > "$@" || ( RV=$$?; rm -f "$@"; exit $${RV} )

byte:
	$(MAKE) all "OPT:=-byte"

opt:
	$(MAKE) all "OPT:=-opt"

install:
	mkdir -p `$(COQC) -where`/user-contrib
	cp -f $(VOFILES) `$(COQC) -where`/user-contrib

Makefile: Make
	mv -f Makefile Makefile.bak
	$(COQBIN)coq_makefile -f Make -o Makefile


clean:
	rm -f *.cmo *.cmi *.cmx *.o $(VOFILES) $(VIFILES) $(GFILES) *~
	rm -f all.ps all-gal.ps all.glob $(VFILES:.v=.glob) $(HTMLFILES) $(GHTMLFILES) $(VFILES:.v=.tex) $(VFILES:.v=.g.tex) $(VFILES:.v=.v.d)
	- rm -rf html

archclean:
	rm -f *.cmx *.o


-include $(VFILES:.v=.v.d)
.SECONDARY: $(VFILES:.v=.v.d)

# WARNING
#
# This Makefile has been automagically generated
# Edit at your own risks !
#
# END OF WARNING

